theme: minima
title: "Zavarka"
description: "Thoughts on how and what we want in scholarly publishing reform."
show_downloads: false
github:
  is_project_page: false
exclude: README.md
baseurl: https://thesamovar.github.io/zavarka