theme: minima
title: "Dan Goodman's publishing blog"
description: "Some miscellaneous thoughts jotted down here for posterity."
show_downloads: false
github:
  is_project_page: false
exclude: README.md
